### ISSUE TITLE
Issue login for Bard

### ISSUE THREAD

**Issue by thoiruddin** [Jun-Murakami/AI_Prompt_Editor#2]
Already tried with 3 different browsers.

Microsoft Edge
Opera
Google Chrome

Here is the error "Couldn’t sign you in. This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can try again to sign in."

**Comment by Jun-Murakami** [comment]
The browser built into this application is equivalent to Chrome.
If you can't log in using any other browser either, then check your OS security and other settings.

**Comment by Jun-Murakami** [comment]
I have found that I am unable to log in with certain Google accounts. Sorry for the delay, but we have made a fix and hope you will try it.
